spring:
  jpa:
    database: MYSQL
  messages:
    encoding: UTF-8
  http:
    encoding:
      charset: UTF-8
  profiles:
    active: dev
  task:
    scheduling:
      pool:
        size: 8
      thread-name-prefix: "explorer-task-"



mybatis:
  check-config-location: true
  type-aliases-package: com.github.ontio.explorer.statistics.model
  mapper-locations: classpath*:**/mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8090
  tomcat:
    uri-encoding: UTF-8

config:
  hosts:
    - http://dappnode1.ont.io:20334
    - http://dappnode2.ont.io:20334
    - http://dappnode3.ont.io:20334
    - http://dappnode4.ont.io:20334
  consensus-node-detail-url: https://explorer.ont.io/nodes/detail/
  node-map-url: http://localhost:8888/api/nodes
  is-test-net: false
